version: "3.9"

services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_flask:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alstacon/skypro_film:latest
    restart: always
    environment:
      POSTGRES_HOST: pg
    ports:
      - "5000:5000"
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 3s
      timeout: 3s
      retries: 5
    depends_on:
      pg:
        condition: service_healthy

  front:
    image: painassasin/node_cource_project:latest
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy




volumes:
  pg_data_flask: