version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data_flask:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alstacon/skypro_film
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  front:
    image: painassasin/node_cource_project:latest
    ports:
      - "80:3000"




volumes:
  pg_data_flask: