version: "3.9"

services:
  front:
    image: painassasin/node_cource_project:latest
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - front

  api:
    image: alstacon/skypro_film:latest
    ports:
      - "5000:5000"
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_HOST: pg
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - back
      - front
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pg_data_flask:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back

volumes:
  pg_data_flask:

networks:
  back:
    driver: bridge
  front:
    driver: bridge


